# Generated by Django 4.0.5 on 2022-07-21 20:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('measurement', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='measurement',
            name='measure_date',
        ),
    ]
